apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn/helmrelease.yaml
  - ../../base/longhorn/helmrepository.yaml
patches:
  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: add
        path: /spec/values/defaultSettings
  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: add
        path: /spec/values/defaultSettings/defaultReplicaCount
        value: 1
  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: add
        path: /spec/values/persistence/reclaimPolicy/defaultClassReplicaCount
        value: 1

  