apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  defaultSettings:
    defaultReplicaCount: 1
  persistence:
    defaultClassReplicaCount: 1