apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      defaultReplicaCount: 3
    persistence:
      retainPolicy: Retain
      defaultClassReplicaCount: 3