apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/uptime-kuma/deployment.yaml
  - ../../base/apps/uptime-kuma/pvc.yaml
  - ../../base/apps/uptime-kuma/service.yaml
  - ../../base/apps/uptime-kuma/ingress.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: uptime-kuma
      namespace: apps