apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/uptime-kuma/statefulset.yaml
  - ../../base/uptime-kuma/service.yaml
  - ../../base/uptime-kuma/ingress.yaml
patches:
  - path: patch.yaml
    target:
      kind: StatefulSet
      name: uptime-kuma
      namespace: staging-apps