name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing Ansible playbooks with Gitea actions
on: [push]

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Ansible 
        run: |
          apt update
          apt install --yes software-properties-common
          add-apt-repository --yes --update ppa:ansible/ansible
          apt install --yes ansible

      - name: Install joshrnoll.homelab Ansible collection
        run: ansible-galaxy collection install joshrnoll.homelab

      - name: Set ssh identity
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo '#!/bin/sh' >> passphrase
          echo 'echo $SSH_PASSPHRASE' >> passphrase
          chmod +x passphrase
          eval `ssh-agent -s`
          echo -n "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=1 SSH_ASKPASS="./passphrase" ssh-add -
          ssh-keyscan -H 10.0.30.40 > /home/runner/.ssh/known_hosts
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: ${{ gitea.workspace }}/ansible/servers/main.yaml
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --inventory ${{ gitea.workspace }}/ansible/hosts.yaml
            --ssh-extra-args "-o StrictHostKeyChecking=no"

