name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing Ansible playbooks with Gitea actions
on: [push,workflow_dispatch]

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install joshrnoll.homelab Ansible collection
        run: ansible-galaxy collection install joshrnoll.homelab

      - name: Set ssh identity
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_VAULT_PW: ${{ secrets.ANSIBLE_VAULT_PW }}
        run: |
          mkdir -p /home/runner/.ssh && touch /home/runner/.ssh/id_rsa
          echo $SSH_PRIVATE_KEY >> /home/runner/.ssh/id_rsa && echo >> /home/runner/.ssh/id_rsa
          chmod 0700 /home/runner/.ssh/id_rsa
          echo -n "$ANSIBLE_VAULT_PW" | tr -d '\r' >> /home/runner/vault-pw
          echo '#!/bin/sh' >> passphrase && echo "echo $SSH_PASSPHRASE" >> passphrase
          chmod +x passphrase
          eval `ssh-agent -s`
          echo -n "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=1 SSH_ASKPASS="./passphrase" ssh-add -
          
      - name: Run playbook
        run: ansible-playbook /workspace/joshrnoll/homelab-as-code/ansible/servers/main.yaml --inventory /workspace/joshrnoll/homelab-as-code/ansible/hosts.yaml --vault-password-file /home/runner/vault-pw --ssh-extra-args "-o StrictHostKeyChecking=no"

