name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing Ansible playbooks with Gitea actions
on: [push,workflow_dispatch]

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install joshrnoll.homelab Ansible collection
        run: ansible-galaxy collection install joshrnoll.homelab

      - name: Set up ssh agent and run playbook
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_VAULT_PW: ${{ secrets.ANSIBLE_VAULT_PW }}
        run: chmod +x /workspace/joshrnoll/homelab-as-code/ansible/run.sh && /workspace/joshrnoll/homelab-as-code/ansible/run.sh

