name: Baseline Proxmox hosts
on: [workflow_dispatch]

jobs:
  baseline_proxmox_machines:
    runs-on: ubuntu-latest-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Proxmox baseline playbook
        uses: joshrnoll/homelab-as-code/.gitea/workflows/run-ansible-playbook.yaml@main
        with:
          playbook_path: /workspace/joshrnoll/homelab-as-code/ansible/servers/main.yaml
          inventory_path: /workspace/joshrnoll/homelab-as-code/ansible/hosts.yaml
        secrets:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PW }}

