---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: staging
  secretRef:
    name: flux-system
  url: https://gitea.nollhome.casa/joshrnoll/homelab-as-code.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
  targetNamespace: staging-apps
  decryption:
    provider: sops
    secretRef:
      name: sops-key
