apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 5m
    chart:
        spec:
            chart: authentik
            version: '*'
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: flux-system
            interval: 5m
    values:
        global:
            namespaceOverride: ENC[AES256_GCM,data:tiS3W3d3iokq,iv:tWhqqRpGIGjMYhK2RfYhRR/eiDxNd+JW3SFgu0Ezq7Q=,tag:M4uf7TBG/+avlbMaSNi7zw==,type:str]
        authentik:
            secret_key: ENC[AES256_GCM,data:UD26TdFiU2tFYvp+lfK9nLTDkI1rRDg+ru+pG7X1m81uhMeL7kaSExIq+UwzVnt6cCRaQwU08J2E/1E3uSJy6S6WoOsHt5LXONL9VyQ1L0o=,iv:22UF9V9puaxSHNpqIgcZyfXjx84tK9tLLkEGosXwgbc=,tag:dSAGhSAYEo5DStEsRyJBNQ==,type:str]
            error_reporting:
                enabled: ENC[AES256_GCM,data:UeXs8JM=,iv:GgF6P0s8vFsq62PvIAuPDmZTivwOQvIiI7ud3w+TzSE=,tag:X/iM22pWAOAMlswQBRrV6w==,type:bool]
            postgresql:
                password: ENC[AES256_GCM,data:IivLTNsDFQlVp8xPG1dOJAvSgVo=,iv:W/N/Sn8+fxRcGUySrIk+DDgUZ63QZgHxlXx2MsGjyJ4=,tag:UqC3MNd09amDFPa7MY1H2w==,type:str]
            email:
                host: ENC[AES256_GCM,data:mml6o1MiO64m0DFFc94=,iv:AAZEikbz6QYK070I35YAlknSi601S/nH3QoEH0b/ais=,tag:uwPOcwQheTh63LXa6QZuEQ==,type:str]
                port: ENC[AES256_GCM,data:GvPu,iv:s4l0v9fkgBuq6N60aCrHWBlLczHr6NuxNeAB1FedVCE=,tag:VxrWI1VUHY3nS2rIN9v9lQ==,type:int]
                username: ENC[AES256_GCM,data:M6SRjSrsv3H6C5dyY69lApbmmLNj,iv:DK3jjcdPo/LLHowReq3wVHCr3yKzm4EzjM8weVfbp84=,tag:hoJC0k0UG/uaRpz9Ph1hNQ==,type:str]
                password: ENC[AES256_GCM,data:ykcbJxSiEpVcTXrMSDVfwrPW1Q==,iv:mfzk/l+PrqHFfutCD209kW/IVivBXlzMKDMqSslGlHk=,tag:l7H+9XJEUq5fnUH9ri4oyA==,type:str]
                use_tls: ENC[AES256_GCM,data:e5jSyA==,iv:/KfdoBlbokPqW0BfIb2AA9mRfaM+/mhw/3CJ/hBtJC0=,tag:vkHaD7LUSkfbtBMwgZsCIg==,type:bool]
                timeout: ENC[AES256_GCM,data:E2A=,iv:X8shGSptSP8f2sfMVr+ZgdHTwNF9ztK+tIlZ1HqWXts=,tag:DaziAuWeqb+jm5OP7Efm4w==,type:int]
                from: ENC[AES256_GCM,data:ydZuORihO1A3j4HCrPBonvZk+mm/RbK6yGTbynruq6UEk45BA0kbSB4I0N5vtGE=,iv:RC0sEQFspYAmvYGC4+igo97M68WDRXv36IqDC8E5qM8=,tag:g14BhpIr15CYsoaF5CoarA==,type:str]
        server:
            ingress:
                enabled: ENC[AES256_GCM,data:V+c8lA==,iv:dqG7U7Y9W6RjXaAddk7OuOO7UGU/RDBmD1XhT3vWiKo=,tag:94ulzfz1dQ0qI6N2KLZUhQ==,type:bool]
                ingressClassName: ENC[AES256_GCM,data:INrF3e4Lnw==,iv:DhYILCEdnN/8W9iHS/xpSLbGw/ZiIAynAtgkFA77BxQ=,tag:6FHmejvL6/80WzYsC/muUg==,type:str]
                hosts:
                    - ENC[AES256_GCM,data:6BcHptqECxa+VVzMBC2N9Gl/6HPjQ1Y=,iv:3kS0DAg77ELRlkYr3Od+BQTxFbylcBvAS9cxI7UpbYE=,tag:tS7e5U4dKcyxEWdmGAJ49g==,type:str]
        postgresql:
            enabled: ENC[AES256_GCM,data:QTSlMA==,iv:rZEEomLAbih8YTumduaY5ZDmCrE1SPfIs/v2bWQ0OU0=,tag:6S6GFkIYKshizZ0qcwFXAw==,type:bool]
            auth:
                password: ENC[AES256_GCM,data:0rj7VXPj6xsT5ZZ/HSD1Ut/h15E=,iv:GdPRZgUfPg+He0+C2fncWEuaYRw7dSH6tFF7bKXHiYA=,tag:ATavBDw/Cyq0MtD64nMagA==,type:str]
        redis:
            enabled: ENC[AES256_GCM,data:C/+4Jg==,iv:qB30opgkO9kH0fIfmCDQaZ6OgtROYamqciul4J1xcYw=,tag:rOvWNQ1NQr07Pb+KjHjFOA==,type:bool]
sops:
    age:
        - recipient: age18dvn87z8hq2e0kak3f5d06xn9ynpcmfkkvep4ch8z32m7hkma3xsmgez3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTanN2Qzk3TjJZa2l2L0s5
            aktBZGpFTXJBTEtuZmVaczluek0rc2g5QXo0CkpuZW84blZZN2lNM0kwTzkwaldx
            bGtHNDkvU3V0WG9CczdTMklFSitQakkKLS0tIHpOVitBb0xwRFduamNlN1ZFYlcx
            MU4zTmZjNkN4ZUZLcmNFU0VZZE5jZFEKvYakukftF9wc9iN2VQNvggXChQ2LGAq0
            rtnyaM3s5uTH14ZES5LjfDpBGFtPa6V7DCu73yygEs2cUhOZ+8UgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T10:53:17Z"
    mac: ENC[AES256_GCM,data:qbK3td0emGnpexlbQx8kXpQcoJ6203H0ydzrIOanI0B6rZ5nADJRWs0YqT/qrbUKEcbdX0bA/n6uK25ixu47Zuz4Q6JdgQYpoXHpFRXnNVG4M1YpK+OliXNw7xVPpOIPt3uStkrzGcFzdeBinsQK/O4F0q7dMdHmFQxrJdFnyxE=,iv:iYeX/KnLAmt7E/WhMeETl6322odt+MnMm7velfqlqF4=,tag:Fqn5g8Nt27hWQ7ZLvY8G5w==,type:str]
    encrypted_regex: ^(values)$
    version: 3.10.2
