apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 5m
    chart:
        spec:
            chart: authentik
            version: '*'
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: flux-system
            valuesFrom:
                - kind: Secret
                  name: authentik-values
            interval: 5m

