apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik/helmrelease.yaml
  - ../../base/traefik/helmrepository.yaml
  - ../../base/traefik/namespace.yaml
  - ../../base/traefik/traefik-values.yaml
patches:
  - path: patch.yaml
    target: 
      kind: ConfigMap
      name: traefik-values