apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik/helmrelease.yaml
  - ../../base/traefik/helmrepository.yaml
  - ../../base/traefik/namespace.yaml
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values=traefik-values.yaml
secretGenerator:
  - name: traefik-secrets
    files:
      - values=../../../secrets/traefik-secret-values.yaml
patches:
  - path: patch.yaml
    target: 
      kind: HelmRelease
      name: traefik
      namespace: traefik