apiVersion: v1
kind: Service
metadata:
  name: uptimekuma-service
  namespace: apps
spec:
  selector:
    app: uptimekuma
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001