apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: tailscale
    namespace: tailscale
spec:
    interval: 5m
    chart:
        spec:
            chart: tailscale-operator
            version: '*'
            sourceRef:
                kind: HelmRepository
                name: tailscale
                namespace: tailscale
            interval: 5m
    values:
        oauth:
            clientId: ENC[AES256_GCM,data:0x8190aulhXupOyZf7NXR8s=,iv:Ufth5dMhCkSYDzfuRkxXUMVMslZyMPGhRyqZh2TswHk=,tag:6GGDkxGVsKj/EvPjNQFrSg==,type:str]
            clientSecret: ENC[AES256_GCM,data:aABjDD+kZ6V0AGYF5xssL/YDn/iEl7yyThftQqy2tsIrV94GHU0hs14xAF4xWY20NSxAsq5fZwPpIFMCFWGz,iv:/hzr5fDal6W3teTWc6tfp3yrLSrpNIQxVbc5Vo7sjBI=,tag:MT5EbrM8b2qIBXtnAmJexg==,type:str]
        extraEnv:
            - name: TS_ACCEPT_DNS
              value: "true"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18dvn87z8hq2e0kak3f5d06xn9ynpcmfkkvep4ch8z32m7hkma3xsmgez3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbUl1T2MwMDhtNkdQcGRO
            MHZYRDZCMkRXZmQyNkN2VmExaFZwYUxvdHljCjhhZ2wxL1ZveFY4OFdSa1RTc3lq
            OFZJTUlQU0grR3l0Ylg0RmQ1TmxrQ2MKLS0tIHZ5emowRzY5VVkyRklNZ3BveStG
            K2NpSXp5eEsreGhBUmhRMlVhS1FLMEUKnesTrzy6aHiLimAReU15McsjxhNg6LVt
            FU6VKY4lvZB99bE+A7S7pNGUfK+/JDsEyGeHCg2PtZGx8Jku5IQong==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T09:41:00Z"
    mac: ENC[AES256_GCM,data:4FQ0yQ9BcTmZTlAciub1mro6O9oRMUesov8JCDkNUgcNciILDuyWRCY3gqFGLRxB8sVS1APdqd54bGuTVkBAKDo4y7v14UzL923KQ+vQBb7zkC4vq0+s4NW9tK3Kr8i+dEYEOU56RKHCESd6+gb2L3QfxN6U42mgAzMsnUgCibY=,iv:uYdrH5LuPi0TSAqjfFW3dZ+aTBxfXb5LSAngMBo+XT0=,tag:pVth/0ldmN89xaWdbUOGCQ==,type:str]
    pgp: []
    encrypted_regex: ^(oauth)$
    version: 3.9.4
