apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 5m
  values:
    valuesFrom:
    - kind: Secret
      name: tailscale-secrets