apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authentik/helmrelease.yaml
  - ../../base/authentik/helmrepository.yaml
  - ../../base/authentik/namespace.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
      name: authentik
      namespace: authentik