apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    server:
      ingress:
        hosts:
        - authentik.staging.nollhome.casa