---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: authentik
spec:
  storageClassName: longhorn
  volumeName: media-pv
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: authentik
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  claimRef:
    name: media-pvc
    namespace: authentik